reading_status:
  - unread
  - reading
  - readed
roles:
  - normal
  - admin
roles_status:
  - Waiting
  - Accept
  - Decline
follow_type:
  - following
  - followers
activity_type_list:
  - favorite
  - read
  - review
  - comment
  - follow
  - unfollow
activity_translate:
  favorite:
   class_name: "Book"
   column: "title"
  read:
   class_name: "Book"
   column: "title"
  review:
   class_name: "Review"
   column: "book.title"
  comment:
   class_name: "Comment"
   column: "review.book.title"
  follow:
   class_name: "User"
   column: "name"
  unfollow:
   class_name: "User"
   column: "name"
number:
  review_per_page: 1
  per_page: 10
  short_miximum: 5
  user_per_page: 15
  user_per_page_2: 6
  count: 5
  round: 2
admin:
  books:
    picture_height: 220
    picture_width: 150
    picture_height300: 420
    picture_width300: 280
    picture_default: "bookdefault2.jpg"
    picture_default_2: "bookdefault2.jpg"
    max_string: 10
    pages: 12
    max_rate: 5
    max_number_page: 50000
    min_number_page: 1
    min_title_length: 6
user:
  gravantar_size230: 230
  gravantar_size150: 150
  max_string: 15
  pages: 12
  picutre_height330: 330
  picture_width250: 250
  admin: 1
favorites:
  create: "create"
  destroy: "destroy"
books:
  picutre_height330: 330
  picture_width250: 250
  mg-left: 100px
  requested_day: 7
review:
  picture_size50: 50
favorite:
  books:
    pages: 6
    suggest_un_favorite_books: 5
notice:
  type:
    success: "success"
    danger: "danger"
    error: "error"
following_type: "following"
follower_type: "followers"
activities:
  pages: 6
mail_default: "no-reply@brs.framgia.com"
